# Generated by Django 3.2.8 on 2024-07-11 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCampo',
            fields=[
                ('idtipocampo', models.AutoField(primary_key=True, serialize=False)),
                ('tipocampo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('idsede', models.AutoField(primary_key=True, serialize=False)),
                ('sede', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('idcampo', models.AutoField(primary_key=True, serialize=False)),
                ('campo', models.CharField(max_length=100)),
                ('idsede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.sede')),
                ('idtipocampo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.tipocampo')),
            ],
        ),
    ]
